Repository jsgalvish/printf, pull requests merged in 2019-07, with the labels that each got.

#10 initialize files
  _printf.c
  character_operations.c
  get_func.c
  holberton.h
  number_operations.c
Labels: good first issue

#12 Sanitaze the input if is NULL
  _printf.c
Labels: feature

#13 Feat/print c
  0-character_operations.c
  _putchar.c
  character_operations.c
  holberton.h
Labels: feature

#14 Add function prototype print_c
  holberton.h
Labels: bug

#15 Fix the argument of the va_arg
  0-character_operations.c
Labels: bug

#18 add print string functionality
  0-character_operations.c
  get_func.c
  holberton.h
Labels: feature

#19 add count print
  _printf.c
Labels: enhancement

#20 Add functionality of read decimal integers
  1-number_operations.c
  get_func.c
  holberton.h
  number_operations.c
Labels: feature

#23 Add man page of the printf
  README.md
  holberton.jpg
  man_3_printf
Labels: enhancement

#25 Add numbers in mode binary
  3-binary.c
  get_func.c
  holberton.h
Labels: feature
